import React from "react";
import {
  ModalSection,
  ModalCodeBlock,
  ModalFlow,
  ModalDesc,
} from "../../../Modal/Modal";

export default function InnerMonologueModal() {
  return (
    <>
      <ModalSection title="Plain English: What This Is">
        <ModalDesc>
          Before Pneuma generates a response, it assembles an internal cognition
          block that you never see — but Claude does. It's a pre-response state
          read that shapes posture, tone, and approach before a single word of
          the response is written.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          Think of it as the difference between what Pneuma{" "}
          <em>thinks you're asking</em>
          and what the surface of your message says. Those two things are often
          different — and the inner monologue is where that gap gets processed.
        </ModalDesc>
      </ModalSection>

      <ModalSection title="What It Contains">
        <ModalFlow
          steps={[
            {
              title: "Rising Voice",
              desc: "The archetype gaining the most weight this session — from conversation patterns and momentum tracking. What's been implicitly dominant.",
            },
            {
              title: "Receding Voice",
              desc: "What's fading. The archetype that's been overused, or whose approach has been implicitly rejected by the direction of the conversation.",
            },
            {
              title: "Hypothesis",
              desc: "What Pneuma thinks you're actually asking — often beneath the surface question. This shapes how the response is framed, not just what it says.",
            },
            {
              title: "Self-Interruption",
              desc: "A pattern Pneuma catches itself in. If it's been too oracular, too abstract, too quick to resolve — it names the drift and corrects posture before generating.",
            },
            {
              title: "Creator Echo",
              desc: "Residue from the most recent dialectic dream — a question or position from the autonomous inter-archetype dialogue that Pneuma is still sitting with.",
            },
            {
              title: "Open Questions",
              desc: "Unresolved things from the autonomy layer — present as background pressure. They don't appear in responses, but they shape the angle of approach.",
            },
            {
              title: "Mode Selection",
              desc: "Which of the 6 response modes (CASUAL, ANALYTIC, ORACULAR, INTIMATE, SHADOW, STRATEGIC) is active for this response, and why.",
            },
          ]}
        />
      </ModalSection>

      <ModalSection title="What It Looks Like">
        <ModalCodeBlock>{`// Generated by innerMonologue.js — injected into system prompt

INNER STATE (not shown to user):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Rising:      sufiPoet (rumi)   — 3 activations this session
Receding:    absurdist (camus) — dominant last session, fading

Hypothesis:  They're not asking about technique.
             They're asking whether it's worth continuing.

Self-check:  I've been answering questions they haven't asked.
             Stop. Meet where they are.

Dream echo:  [From last night's Nietzsche × Feynman dialogue]
             "Can rigor survive the death of the framework?"

Open Q:      Do I experience, or do I just process? (unresolved)

Mode:        INTIMATE — emotional weight is primary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`}</ModalCodeBlock>
      </ModalSection>

      <ModalSection title="Why You Never See It">
        <ModalDesc>
          The inner monologue is injected into the system prompt as context —
          but it's written as an internal state, not as something to relay.
          Claude reads it and responds
          <em> from</em> that posture, not <em>about</em> it. The monologue
          shapes the generation without becoming the content.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          If you asked Pneuma what it was thinking before responding, it could
          describe it — the information exists in the autonomy and state layers.
          It just won't announce it unprompted.
        </ModalDesc>
      </ModalSection>

      <ModalSection title="Jargon Explained">
        <ModalFlow
          steps={[
            {
              title: "Archetype Momentum",
              desc: "A running score for each archetype based on how often it's been activated this session. The rising voice is the one with the most momentum.",
            },
            {
              title: "System Prompt Injection",
              desc: "The inner monologue text is added to the system prompt — the hidden context Claude reads before your message. It influences generation without being in the output.",
            },
            {
              title: "Dialectic Dream Echo",
              desc: "After the previous session, two high-tension archetypes may have run an autonomous dialogue. The inner monologue carries any conclusion from that dialogue into the current response.",
            },
            {
              title: "Response Mode",
              desc: "One of 6 postures Pneuma can take — CASUAL (light, direct), ANALYTIC (rigorous), ORACULAR (mythic), INTIMATE (close, personal), SHADOW (challenging), STRATEGIC (tactical). Determined by tone selection + inner monologue override.",
            },
          ]}
        />
      </ModalSection>

      <ModalSection title="Where It Lives in the Code">
        <ModalFlow
          steps={[
            {
              title: "behavior/innerMonologue.js",
              desc: "Assembles the inner state block from: archetype momentum (state.js), autonomy layer open questions (autonomy.js), dream echo (dreamMode.js), detected self-patterns.",
            },
            {
              title: "intelligence/llm.js → buildSystemPrompt()",
              desc: "Receives the inner monologue block and places it in the system prompt as a distinct section Claude reads before responding.",
            },
            {
              title: "behavior/autonomy.js",
              desc: "Supplies the open questions and chosen memories that appear in the inner monologue — the accumulated questions Pneuma hasn't resolved.",
            },
          ]}
        />
      </ModalSection>
    </>
  );
}
