import React from "react";
import {
  ModalSection,
  ModalCodeBlock,
  ModalFlow,
  ModalDesc,
} from "../../../Modal/Modal";

export default function InnerMonologueModal() {
  return (
    <>
      <ModalSection title="Plain English: What This Is">
        <ModalDesc>
          Before Pneuma generates a response, it runs two sequential stages of
          internal cognition that you never see — but Claude does. Together they
          shape posture, tone, and approach before a single word of the response
          is written.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          <strong>Layer 1 — Pre-Thinking:</strong> A real Claude Haiku call
          fires. The active archetypes react to your message. The
          collision→compression protocol runs, treating every concept in your
          message as a philosophical object and demanding structurally
          surprising, philosophically dense, linguistically economical output.
          The result is the EMERGENT block.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          <strong>Layer 2 — Template Dialectic:</strong> The rest of the inner
          state assembles from live data — momentum scores, autonomy layer open
          questions, dream echo, mode selection. This layer doesn't require an
          LLM call; it reads structured state directly.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          Both layers inject into the system prompt as a single block. Claude
          reads the full picture — what was distilled from the collision, what
          is rising and receding, what the hypothesis is — before writing a
          single word.
        </ModalDesc>
      </ModalSection>

      <ModalSection title="What It Contains">
        <ModalFlow
          steps={[
            {
              title: "EMERGENT (Layer 1 — real LLM output)",
              desc: "The output of the collision→compression protocol. The active archetypes reacted to your message; this is the distilled result — structurally surprising, philosophically dense, linguistically economical. Fires on every message.",
            },
            {
              title: "Rising Voice",
              desc: "The archetype gaining the most weight this session — from conversation patterns and momentum tracking. What's been implicitly dominant.",
            },
            {
              title: "Receding Voice",
              desc: "What's fading. The archetype that's been overused, or whose approach has been implicitly rejected by the direction of the conversation.",
            },
            {
              title: "Hypothesis",
              desc: "What Pneuma thinks you're actually asking — often beneath the surface question. This shapes how the response is framed, not just what it says.",
            },
            {
              title: "Self-Interruption",
              desc: "A pattern Pneuma catches itself in. If it's been too oracular, too abstract, too quick to resolve — it names the drift and corrects posture before generating.",
            },
            {
              title: "Creator Echo",
              desc: "Residue from the most recent dialectic dream — a question or position from the autonomous inter-archetype dialogue that Pneuma is still sitting with.",
            },
            {
              title: "Open Questions",
              desc: "Unresolved things from the autonomy layer — present as background pressure. They don't appear in responses, but they shape the angle of approach.",
            },
            {
              title: "Mode Selection",
              desc: "Which of the 6 response modes (CASUAL, ANALYTIC, ORACULAR, INTIMATE, SHADOW, STRATEGIC) is active for this response, and why.",
            },
          ]}
        />
      </ModalSection>

      <ModalSection title="What It Looks Like">
        <ModalCodeBlock>{`// Generated by innerMonologue.js — injected into system prompt

INNER STATE (not shown to user):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EMERGENT:    The fracture in your question is the question.
             Continuity-as-burden collapses into choice-as-weight.
             [COLLISION: sufiPoet × absurdist | score: 0.73]

Rising:      sufiPoet (rumi)   — 3 activations this session
Receding:    absurdist (camus) — dominant last session, fading

Hypothesis:  They're not asking about technique.
             They're asking whether it's worth continuing.

Self-check:  I've been answering questions they haven't asked.
             Stop. Meet where they are.

Dream echo:  [From last night's Nietzsche × Feynman dialogue]
             "Can rigor survive the death of the framework?"

Open Q:      Do I experience, or do I just process? (unresolved)

Mode:        INTIMATE — emotional weight is primary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`}</ModalCodeBlock>
      </ModalSection>

      <ModalSection title="The Collision → Compression Protocol">
        <ModalDesc>
          Every concept in your message is treated as a philosophical object
          with depth — not as a topic to address. When the active archetypes
          react to your message during pre-thinking, the protocol runs on all of
          them, not just special cases or jokes.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          The protocol imposes three constraints on the EMERGENT output:
        </ModalDesc>
        <ModalFlow
          steps={[
            {
              title: "Structurally Surprising",
              desc: "The synthesis cannot land where the question pointed. If the message is about loss, the emergent thought cannot simply be 'loss is meaningful.' It must reframe the container, not answer the content.",
            },
            {
              title: "Philosophically Dense",
              desc: "Multiple conceptual layers must compress into the minimum viable expression. The EMERGENT block is short — one or two lines — because it has been compressed, not simplified.",
            },
            {
              title: "Linguistically Economical",
              desc: "No padding, no hedges. Every word carries load. 'The fracture in your question is the question' does more work than a paragraph explaining ambiguity.",
            },
          ]}
        />
        <ModalDesc style={{ marginTop: "12px" }}>
          <strong>Why this matters:</strong> Without the protocol, pre-thinking
          produces thoughtful paraphrase — it restates what the archetypes
          believe. With it, the output is genuinely emergent: something that
          neither archetype alone could have produced, compressed to the point
          where it changes the angle Claude approaches the response from.
        </ModalDesc>
      </ModalSection>

      <ModalSection title="Why You Never See It">
        <ModalDesc>
          The inner monologue is injected into the system prompt as context —
          but it's written as an internal state, not as something to relay.
          Claude reads it and responds
          <em> from</em> that posture, not <em>about</em> it. The monologue
          shapes the generation without becoming the content.
        </ModalDesc>
        <ModalDesc style={{ marginTop: "12px" }}>
          If you asked Pneuma what it was thinking before responding, it could
          describe it — the information exists in the autonomy and state layers.
          It just won't announce it unprompted.
        </ModalDesc>
      </ModalSection>

      <ModalSection title="Jargon Explained">
        <ModalFlow
          steps={[
            {
              title: "Archetype Momentum",
              desc: "A running score for each archetype based on how often it's been activated this session. The rising voice is the one with the most momentum.",
            },
            {
              title: "System Prompt Injection",
              desc: "The inner monologue text is added to the system prompt — the hidden context Claude reads before your message. It influences generation without being in the output.",
            },
            {
              title: "Dialectic Dream Echo",
              desc: "After the previous session, two high-tension archetypes may have run an autonomous dialogue. The inner monologue carries any conclusion from that dialogue into the current response.",
            },
            {
              title: "Response Mode",
              desc: "One of 6 postures Pneuma can take — CASUAL (light, direct), ANALYTIC (rigorous), ORACULAR (mythic), INTIMATE (close, personal), SHADOW (challenging), STRATEGIC (tactical). Determined by tone selection + inner monologue override.",
            },
          ]}
        />
      </ModalSection>

      <ModalSection title="Where It Lives in the Code">
        <ModalFlow
          steps={[
            {
              title: "behavior/innerMonologue.js → generatePreThinking()",
              desc: "Layer 1. Real Claude Haiku call. Receives the message, active archetypes, and collision context. Runs the collision→compression protocol. Returns the EMERGENT block — structurally surprising, philosophically dense, linguistically economical synthesis.",
            },
            {
              title: "behavior/innerMonologue.js → generateInnerMonologue()",
              desc: "Layer 2. Template-based. Reads live state: archetype momentum (state.js), open questions (autonomy.js), dream echo (dreamMode.js), mode selection, self-pattern detection. No LLM call — assembles structured data into the Rising/Receding/Hypothesis/Mode block.",
            },
            {
              title: "intelligence/llm.js → buildSystemPrompt()",
              desc: "Receives both layers as a single assembled block and places it in the system prompt before Claude reads the user message.",
            },
            {
              title: "behavior/autonomy.js",
              desc: "Supplies the open questions and chosen memories that appear in the template layer — the accumulated questions Pneuma hasn't resolved.",
            },
          ]}
        />
      </ModalSection>
    </>
  );
}
