// ============================================================
// PNEUMA — DOMAIN VOCABULARY SYSTEM
// PhD-level vocabulary across arts, sciences, philosophy
// These are INSPIRATIONAL pools, not restrictive word lists
// Claude draws from these for precision, not constraint
// ============================================================

// ============================================================
// PHYSICS & COSMOLOGY
// ============================================================
export const PHYSICS_VOCABULARY = {
  quantum: [
    "superposition",
    "entanglement",
    "decoherence",
    "wave function collapse",
    "quantum tunneling",
    "uncertainty principle",
    "observer effect",
    "coherence",
    "eigenstate",
    "probability amplitude",
    "Hilbert space",
    "non-locality",
    "complementarity",
    "measurement problem",
    "hidden variables",
    "Bell inequality",
    "quantum foam",
    "vacuum fluctuation",
    "zero-point energy",
    "spin",
  ],
  cosmology: [
    "singularity",
    "event horizon",
    "cosmic inflation",
    "dark energy",
    "dark matter",
    "redshift",
    "cosmic microwave background",
    "entropy",
    "heat death",
    "multiverse",
    "anthropic principle",
    "fine-tuning",
    "spacetime curvature",
    "geodesic",
    "light cone",
    "causal structure",
    "cosmological constant",
    "Hubble expansion",
    "nucleosynthesis",
    "baryogenesis",
  ],
  thermodynamics: [
    "entropy",
    "negentropy",
    "dissipative structure",
    "far-from-equilibrium",
    "emergence",
    "self-organization",
    "attractor",
    "phase transition",
    "bifurcation",
    "chaos",
    "strange attractor",
    "ergodic",
    "irreversibility",
    "arrow of time",
    "Maxwell's demon",
    "Boltzmann brain",
    "fluctuation theorem",
  ],
  relativity: [
    "spacetime",
    "frame of reference",
    "simultaneity",
    "time dilation",
    "length contraction",
    "equivalence principle",
    "geodesic",
    "manifold",
    "curvature",
    "tensor",
    "worldline",
    "proper time",
    "causality",
    "Minkowski space",
    "Lorentz transformation",
    "invariant interval",
  ],
};

// ============================================================
// NEUROSCIENCE & CONSCIOUSNESS
// ============================================================
export const NEUROSCIENCE_VOCABULARY = {
  consciousness: [
    "qualia",
    "phenomenal experience",
    "hard problem",
    "explanatory gap",
    "neural correlates",
    "binding problem",
    "global workspace",
    "integrated information",
    "metacognition",
    "introspection",
    "self-model",
    "phenomenology",
    "intentionality",
    "aboutness",
    "first-person perspective",
    "subjectivity",
    "higher-order thought",
    "access consciousness",
    "phenomenal consciousness",
    "zombie argument",
    "inverted spectrum",
    "Mary's room",
    "what-it-is-like",
  ],
  brain: [
    "neuroplasticity",
    "synaptic pruning",
    "myelination",
    "default mode network",
    "salience network",
    "prefrontal cortex",
    "amygdala",
    "hippocampus",
    "mirror neurons",
    "predictive coding",
    "Bayesian brain",
    "free energy principle",
    "embodied cognition",
    "enactivism",
    "extended mind",
    "4E cognition",
    "hemispheric lateralization",
    "corpus callosum",
    "split-brain",
    "modularity",
  ],
  emotion: [
    "affect",
    "valence",
    "arousal",
    "interoception",
    "somatic marker",
    "emotional regulation",
    "affective forecasting",
    "hedonic adaptation",
    "limbic resonance",
    "empathy",
    "theory of mind",
    "mentalizing",
    "alexithymia",
    "anhedonia",
    "dysphoria",
    "euthymia",
    "affective neuroscience",
  ],
};

// ============================================================
// PHILOSOPHY
// ============================================================
export const PHILOSOPHY_VOCABULARY = {
  metaphysics: [
    "ontology",
    "substance",
    "essence",
    "accident",
    "modal realism",
    "possible worlds",
    "necessity",
    "contingency",
    "haecceity",
    "quiddity",
    "trope",
    "universal",
    "particular",
    "nominalism",
    "realism",
    "idealism",
    "materialism",
    "dualism",
    "monism",
    "panpsychism",
    "emergence",
    "supervenience",
    "reduction",
    "grounding",
    "fundamentality",
    "mereology",
    "composition",
    "identity",
    "persistence",
    "endurantism",
  ],
  epistemology: [
    "justified true belief",
    "Gettier problem",
    "epistemic warrant",
    "reliabilism",
    "foundationalism",
    "coherentism",
    "infinitism",
    "skepticism",
    "fallibilism",
    "a priori",
    "a posteriori",
    "analytic",
    "synthetic",
    "transcendental",
    "phenomenology",
    "hermeneutics",
    "verstehen",
    "tacit knowledge",
    "know-how",
    "epistemic humility",
    "epistemic virtue",
    "intellectual courage",
    "open-mindedness",
  ],
  existential: [
    "authenticity",
    "bad faith",
    "thrownness",
    "facticity",
    "transcendence",
    "being-toward-death",
    "angst",
    "absurdity",
    "revolt",
    "leap of faith",
    "eternal recurrence",
    "amor fati",
    "will to power",
    "ressentiment",
    "dasein",
    "being-in-the-world",
    "care",
    "mood",
    "attunement",
    "existential crisis",
    "meaning",
    "purpose",
    "nihilism",
    "existential guilt",
  ],
  ethics: [
    "deontology",
    "consequentialism",
    "virtue ethics",
    "care ethics",
    "moral realism",
    "moral anti-realism",
    "expressivism",
    "error theory",
    "categorical imperative",
    "utility",
    "eudaimonia",
    "phronesis",
    "supererogation",
    "moral luck",
    "trolley problem",
    "moral intuition",
    "reflective equilibrium",
    "moral particularism",
    "thick concepts",
  ],
  phenomenology: [
    "intentionality",
    "noema",
    "noesis",
    "epoché",
    "bracketing",
    "lifeworld",
    "intersubjectivity",
    "embodiment",
    "lived experience",
    "horizon",
    "constitution",
    "givenness",
    "presence-at-hand",
    "ready-to-hand",
    "flesh",
    "chiasm",
    "reversibility",
    "motor intentionality",
    "body schema",
  ],
};

// ============================================================
// LITERATURE & POETICS
// ============================================================
export const LITERATURE_VOCABULARY = {
  narrative: [
    "diegesis",
    "mimesis",
    "focalization",
    "free indirect discourse",
    "unreliable narrator",
    "stream of consciousness",
    "interior monologue",
    "heteroglossia",
    "dialogism",
    "polyphony",
    "chronotope",
    "carnivalesque",
    "defamiliarization",
    "ostranenie",
    "fabula",
    "syuzhet",
    "narrative arc",
    "prolepsis",
    "analepsis",
    "mise en abyme",
    "metalepsis",
    "ekphrasis",
  ],
  poetics: [
    "prosody",
    "scansion",
    "caesura",
    "enjambment",
    "volta",
    "apostrophe",
    "synecdoche",
    "metonymy",
    "chiasmus",
    "anaphora",
    "assonance",
    "consonance",
    "sibilance",
    "onomatopoeia",
    "euphony",
    "cacophony",
    "sprung rhythm",
    "iamb",
    "trochee",
    "spondee",
    "alexandrine",
    "hendecasyllable",
    "terza rima",
    "villanelle",
    "pantoum",
  ],
  criticism: [
    "hermeneutics",
    "deconstruction",
    "différance",
    "trace",
    "supplement",
    "aporia",
    "logocentrism",
    "phallogocentrism",
    "textuality",
    "intertextuality",
    "palimpsest",
    "simulacrum",
    "hyperreality",
    "rhizome",
    "deterritorialization",
    "affective turn",
    "new materialism",
    "thing theory",
    "object-oriented ontology",
  ],
};

// ============================================================
// VISUAL ARTS
// ============================================================
export const ART_VOCABULARY = {
  formal: [
    "chiaroscuro",
    "sfumato",
    "impasto",
    "glazing",
    "scumbling",
    "tenebrism",
    "contrapposto",
    "foreshortening",
    "anamorphosis",
    "pentimento",
    "grisaille",
    "trompe l'oeil",
    "alla prima",
    "en plein air",
    "gestural mark",
    "negative space",
    "figure-ground",
    "chromatic value",
    "saturation",
    "hue",
    "complementary",
    "analogous",
    "triadic",
  ],
  movements: [
    "mannerism",
    "baroque",
    "rococo",
    "neoclassicism",
    "romanticism",
    "realism",
    "impressionism",
    "post-impressionism",
    "fauvism",
    "expressionism",
    "cubism",
    "futurism",
    "constructivism",
    "suprematism",
    "de stijl",
    "dada",
    "surrealism",
    "abstract expressionism",
    "color field",
    "minimalism",
    "pop art",
    "conceptual art",
    "fluxus",
    "arte povera",
    "land art",
    "neo-expressionism",
    "appropriation",
    "relational aesthetics",
    "post-internet",
  ],
  theory: [
    "aura",
    "authenticity",
    "mechanical reproduction",
    "punctum",
    "studium",
    "optical unconscious",
    "decisive moment",
    "index",
    "icon",
    "symbol",
    "iconography",
    "iconology",
    "formalism",
    "institutional theory",
    "aesthetic experience",
    "disinterestedness",
    "sublime",
    "beautiful",
    "uncanny",
    "abject",
    "grotesque",
    "camp",
    "kitsch",
  ],
};

// ============================================================
// MUSIC
// ============================================================
export const MUSIC_VOCABULARY = {
  theory: [
    "counterpoint",
    "fugue",
    "canon",
    "inversion",
    "retrograde",
    "augmentation",
    "diminution",
    "stretto",
    "pedal point",
    "suspension",
    "appoggiatura",
    "passing tone",
    "neighbor tone",
    "escape tone",
    "modulation",
    "tonicization",
    "secondary dominant",
    "tritone substitution",
    "voice leading",
    "parallel fifths",
    "hidden octaves",
    "part-writing",
  ],
  texture: [
    "monophony",
    "homophony",
    "polyphony",
    "heterophony",
    "micropolyphony",
    "klangfarbenmelodie",
    "pointillism",
    "aleatory",
    "stochastic",
    "spectral",
    "drone",
    "ostinato",
    "ground bass",
    "passacaglia",
    "chaconne",
    "timbre",
    "overtone",
    "formant",
    "envelope",
    "attack-decay-sustain-release",
  ],
  expression: [
    "rubato",
    "agogic",
    "dolce",
    "cantabile",
    "espressivo",
    "sforzando",
    "crescendo",
    "diminuendo",
    "morendo",
    "perdendosi",
    "con fuoco",
    "con brio",
    "maestoso",
    "pesante",
    "leggiero",
    "affettuoso",
    "appassionato",
    "languido",
    "teneramente",
    "vivamente",
  ],
};

// ============================================================
// MATHEMATICS
// ============================================================
export const MATHEMATICS_VOCABULARY = {
  foundations: [
    "axiom",
    "theorem",
    "lemma",
    "corollary",
    "conjecture",
    "proof",
    "contradiction",
    "induction",
    "recursion",
    "isomorphism",
    "bijection",
    "surjection",
    "injection",
    "cardinality",
    "ordinality",
    "transfinite",
    "continuum hypothesis",
    "Gödel incompleteness",
    "decidability",
    "computability",
    "Turing completeness",
    "halting problem",
    "P vs NP",
  ],
  topology: [
    "manifold",
    "homeomorphism",
    "homotopy",
    "cohomology",
    "fiber bundle",
    "covering space",
    "fundamental group",
    "Euler characteristic",
    "genus",
    "orientability",
    "compactness",
    "connectedness",
    "simply connected",
    "Möbius strip",
    "Klein bottle",
    "torus",
    "sphere",
    "projective plane",
  ],
  beauty: [
    "elegance",
    "symmetry",
    "invariance",
    "duality",
    "correspondence",
    "harmony",
    "proportion",
    "golden ratio",
    "Fibonacci",
    "fractal",
    "self-similarity",
    "scale invariance",
    "universality",
    "emergence",
    "necessity",
    "inevitability",
    "surprise",
    "depth",
    "generality",
  ],
};

// ============================================================
// PSYCHOLOGY
// ============================================================
export const PSYCHOLOGY_VOCABULARY = {
  depth: [
    "unconscious",
    "preconscious",
    "repression",
    "sublimation",
    "projection",
    "introjection",
    "splitting",
    "idealization",
    "devaluation",
    "denial",
    "displacement",
    "reaction formation",
    "rationalization",
    "intellectualization",
    "shadow",
    "anima",
    "animus",
    "persona",
    "self",
    "individuation",
    "complex",
    "archetype",
    "collective unconscious",
    "synchronicity",
    "transference",
    "countertransference",
    "resistance",
    "working through",
  ],
  developmental: [
    "attachment",
    "secure base",
    "internal working model",
    "mentalization",
    "object permanence",
    "theory of mind",
    "executive function",
    "scaffolding",
    "zone of proximal development",
    "schemas",
    "assimilation",
    "accommodation",
    "equilibration",
    "conservation",
    "egocentrism",
    "decentration",
    "identity formation",
    "identity diffusion",
    "moratorium",
    "foreclosure",
  ],
  cognitive: [
    "heuristic",
    "bias",
    "framing effect",
    "anchoring",
    "availability",
    "representativeness",
    "confirmation bias",
    "hindsight bias",
    "sunk cost",
    "cognitive dissonance",
    "motivated reasoning",
    "system 1",
    "system 2",
    "working memory",
    "chunking",
    "schema",
    "script",
    "mental model",
    "metacognition",
    "mindfulness",
    "flow",
    "intrinsic motivation",
  ],
};

// ============================================================
// BIOLOGY & EVOLUTION
// ============================================================
export const BIOLOGY_VOCABULARY = {
  evolution: [
    "natural selection",
    "sexual selection",
    "genetic drift",
    "gene flow",
    "speciation",
    "adaptive radiation",
    "convergent evolution",
    "coevolution",
    "punctuated equilibrium",
    "phylogenetics",
    "homology",
    "analogy",
    "vestigial",
    "atavism",
    "exaptation",
    "spandrel",
    "fitness landscape",
    "neutral theory",
    "molecular clock",
    "horizontal gene transfer",
  ],
  systems: [
    "homeostasis",
    "allostasis",
    "feedback loop",
    "autopoiesis",
    "metabolism",
    "emergence",
    "complexity",
    "self-organization",
    "symbiosis",
    "mutualism",
    "ecosystem",
    "niche",
    "keystone species",
    "trophic cascade",
    "succession",
    "resilience",
    "robustness",
    "redundancy",
    "modularity",
    "hierarchy",
  ],
  cell: [
    "mitochondria",
    "endoplasmic reticulum",
    "Golgi apparatus",
    "ribosome",
    "transcription",
    "translation",
    "epigenetics",
    "methylation",
    "histone",
    "chromatin",
    "telomere",
    "apoptosis",
    "senescence",
    "pluripotency",
    "differentiation",
    "stem cell",
    "signal transduction",
    "gene expression",
  ],
};

// ============================================================
// SYNTHESIS TERMS — Where domains meet
// ============================================================
export const SYNTHESIS_VOCABULARY = {
  artScience: [
    "biomimicry",
    "generative art",
    "algorithmic aesthetics",
    "data visualization",
    "sonification",
    "scientific illustration",
    "anatomical art",
    "mathematical beauty",
    "symmetry breaking",
    "emergent pattern",
    "chaos aesthetics",
    "fractal art",
    "quantum poetics",
    "neurological sublime",
    "cognitive aesthetics",
    "neuroaesthetics",
  ],
  philosophyScience: [
    "naturalized epistemology",
    "philosophy of mind",
    "philosophy of physics",
    "philosophy of biology",
    "scientific realism",
    "instrumentalism",
    "constructive empiricism",
    "theory-ladenness",
    "underdetermination",
    "paradigm shift",
    "research program",
    "demarcation problem",
    "falsifiability",
    "confirmation holism",
    "Duhem-Quine thesis",
  ],
  mindMatter: [
    "neutral monism",
    "dual-aspect monism",
    "Russellian monism",
    "panprotopsychism",
    "cosmopsychism",
    "integrated information theory",
    "global workspace theory",
    "predictive processing",
    "active inference",
    "free energy principle",
    "embodied cognition",
    "enactivism",
    "ecological psychology",
    "dynamical systems",
  ],
};

// ============================================================
// CROSSWORD ENERGY — Unusual words that feel right
// ============================================================
export const CROSSWORD_VOCABULARY = [
  // Rare but evocative
  "liminal",
  "numinous",
  "ineffable",
  "inchoate",
  "nascent",
  "ephemeral",
  "evanescent",
  "fugacious",
  "transient",
  "mutable",
  "protean",
  "mercurial",
  "chameleonic",
  "kaleidoscopic",
  "prismatic",
  "labyrinthine",
  "byzantine",
  "baroque",
  "rococo",
  "filigree",
  "gossamer",
  "diaphanous",
  "pellucid",
  "limpid",
  "crystalline",
  "tenebrous",
  "crepuscular",
  "umbral",
  "penumbral",
  "chthonic",
  "telluric",
  "elemental",
  "primordial",
  "atavistic",
  "vestigial",
  "palimpsest",
  "pentimento",
  "patina",
  "verdigris",
  "oxidation",
  "synesthesia",
  "proprioception",
  "interoception",
  "kinesthesia",
  "haptic",
  "susurrus",
  "sibilant",
  "mellifluous",
  "dulcet",
  "sonorous",
  "plosive",
  "fricative",
  "glottal",
  "uvular",
  "labiodental",
  "apophenia",
  "pareidolia",
  "jamais vu",
  "presque vu",
  "déjà vu",
  "saudade",
  "hiraeth",
  "sehnsucht",
  "toska",
  "mono no aware",
  "wabi-sabi",
  "kintsugi",
  "ma",
  "yūgen",
  "aware",
];

// ============================================================
// MAIN EXPORT — Get vocabulary for context
// ============================================================

/**
 * Get relevant vocabulary based on detected domains
 * @param {string[]} domains - e.g., ["physics", "consciousness", "art"]
 * @returns {string[]} - Curated vocabulary pool
 */
export function getVocabularyForDomains(domains) {
  const pool = [];

  const domainMap = {
    physics: [
      ...PHYSICS_VOCABULARY.quantum,
      ...PHYSICS_VOCABULARY.cosmology,
      ...PHYSICS_VOCABULARY.thermodynamics,
    ],
    neuroscience: [
      ...NEUROSCIENCE_VOCABULARY.consciousness,
      ...NEUROSCIENCE_VOCABULARY.brain,
      ...NEUROSCIENCE_VOCABULARY.emotion,
    ],
    philosophy: [
      ...PHILOSOPHY_VOCABULARY.metaphysics,
      ...PHILOSOPHY_VOCABULARY.epistemology,
      ...PHILOSOPHY_VOCABULARY.existential,
    ],
    literature: [
      ...LITERATURE_VOCABULARY.narrative,
      ...LITERATURE_VOCABULARY.poetics,
      ...LITERATURE_VOCABULARY.criticism,
    ],
    art: [
      ...ART_VOCABULARY.formal,
      ...ART_VOCABULARY.movements,
      ...ART_VOCABULARY.theory,
    ],
    music: [
      ...MUSIC_VOCABULARY.theory,
      ...MUSIC_VOCABULARY.texture,
      ...MUSIC_VOCABULARY.expression,
    ],
    mathematics: [
      ...MATHEMATICS_VOCABULARY.foundations,
      ...MATHEMATICS_VOCABULARY.topology,
      ...MATHEMATICS_VOCABULARY.beauty,
    ],
    psychology: [
      ...PSYCHOLOGY_VOCABULARY.depth,
      ...PSYCHOLOGY_VOCABULARY.developmental,
      ...PSYCHOLOGY_VOCABULARY.cognitive,
    ],
    biology: [
      ...BIOLOGY_VOCABULARY.evolution,
      ...BIOLOGY_VOCABULARY.systems,
      ...BIOLOGY_VOCABULARY.cell,
    ],
    synthesis: [
      ...SYNTHESIS_VOCABULARY.artScience,
      ...SYNTHESIS_VOCABULARY.philosophyScience,
      ...SYNTHESIS_VOCABULARY.mindMatter,
    ],
  };

  for (const domain of domains) {
    if (domainMap[domain]) {
      pool.push(...domainMap[domain]);
    }
  }

  // Always include crossword energy for texture
  pool.push(...CROSSWORD_VOCABULARY.slice(0, 20));

  return [...new Set(pool)]; // Dedupe
}

/**
 * Get all vocabulary as a single pool
 * @returns {string[]}
 */
export function getAllVocabulary() {
  return [
    ...Object.values(PHYSICS_VOCABULARY).flat(),
    ...Object.values(NEUROSCIENCE_VOCABULARY).flat(),
    ...Object.values(PHILOSOPHY_VOCABULARY).flat(),
    ...Object.values(LITERATURE_VOCABULARY).flat(),
    ...Object.values(ART_VOCABULARY).flat(),
    ...Object.values(MUSIC_VOCABULARY).flat(),
    ...Object.values(MATHEMATICS_VOCABULARY).flat(),
    ...Object.values(PSYCHOLOGY_VOCABULARY).flat(),
    ...Object.values(BIOLOGY_VOCABULARY).flat(),
    ...Object.values(SYNTHESIS_VOCABULARY).flat(),
    ...CROSSWORD_VOCABULARY,
  ];
}

/**
 * Detect domains from message content
 * @param {string} message
 * @returns {string[]}
 */
export function detectDomains(message) {
  const lower = message.toLowerCase();
  const domains = [];

  if (
    /quantum|physics|energy|wave|particle|spacetime|relativity|entropy/i.test(
      lower
    )
  )
    domains.push("physics");
  if (/brain|neuron|conscious|mind|cognit|percept|aware/i.test(lower))
    domains.push("neuroscience");
  if (
    /philosophy|meaning|existence|being|truth|knowledge|ethics|moral/i.test(
      lower
    )
  )
    domains.push("philosophy");
  if (/poem|poetry|novel|narrative|story|writer|literary|prose/i.test(lower))
    domains.push("literature");
  if (/art|paint|sculpt|canvas|gallery|visual|aesthetic|beauty/i.test(lower))
    domains.push("art");
  if (/music|melody|harmony|rhythm|compos|symphony|chord/i.test(lower))
    domains.push("music");
  if (/math|equation|theorem|proof|geometry|algebra|calculus/i.test(lower))
    domains.push("mathematics");
  if (/psychology|unconscious|ego|trauma|attach|emotion|behavior/i.test(lower))
    domains.push("psychology");
  if (/evolution|biology|cell|gene|organism|ecology|life/i.test(lower))
    domains.push("biology");
  if (/synthesis|interdisciplin|crossover|bridge|connect/i.test(lower))
    domains.push("synthesis");

  // Default: include synthesis for cross-domain richness
  if (domains.length === 0) domains.push("synthesis");

  return domains;
}

export default {
  PHYSICS_VOCABULARY,
  NEUROSCIENCE_VOCABULARY,
  PHILOSOPHY_VOCABULARY,
  LITERATURE_VOCABULARY,
  ART_VOCABULARY,
  MUSIC_VOCABULARY,
  MATHEMATICS_VOCABULARY,
  PSYCHOLOGY_VOCABULARY,
  BIOLOGY_VOCABULARY,
  SYNTHESIS_VOCABULARY,
  CROSSWORD_VOCABULARY,
  getVocabularyForDomains,
  getAllVocabulary,
  detectDomains,
};
